### ISSUE TITLE
Docker automated

### ISSUE THREAD

**Issue by lemos1235** [yinxin630/fiora#47]
建议：弄一下 docker 自动构建：-> [link](https://docs.docker.com/docker-hub/builds/)
省略掉 build 的时间

Dockerfile
```
FROM node:alpine

WORKDIR /usr/src/app

Run wget -q -O - https://api.github.com/repos/yinxin630/fiora/tarball/master | tar xz --strip=1 && \
    apk add --no-cache python build-base && \
    yarn install && \
    yarn build && \
    rm -rf public/* && \
    mv dist/fiora/* public

CMD [ "node", "server/main.js" ]
```
或者

```
FROM node:alpine

WORKDIR /usr/src/app

Run  apk add --no-cache python build-base

COPY package.json .

RUN yarn install

COPY . .

RUN yarn build && rm -rf public/* && mv dist/fiora/* public

CMD [ "node", "server/main.js" ]
```

**Comment by yinxin630** [comment]
感谢, docker我就简单看过, 玩的不熟, 有空我研究下哈

**Comment by lemos1235** [comment]
docker-compose.yaml

```
version: '3.2'

services:
  fiora:
    build: .
    restart: always
    ports:
      - "9200:9200"
   environment:
      - "DATABASE=mongodb"
  mongodb:
    image: mongo
    restart: always
```
将 Dockerfile 与 docker-compose.yaml 添加到项目根目录，执行下面的命令用于快速构建并启动项目
```
docker-compose up -d
